-- 002_trees.sql
-- Domain tables: species, trees, observations, observation_photos, tree_detail_history
-- Requires PostGIS for geometry + spatial indexes.

BEGIN;

-- 1) PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2) Approval status enum (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_status') THEN
    CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected');
  END IF;
END
$$;

-- 3) Species
CREATE TABLE IF NOT EXISTS species (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  common_name     VARCHAR,
  scientific_name VARCHAR,
  gbif_taxon_key  INT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Optional: if you expect gbif_taxon_key to be unique when present
-- CREATE UNIQUE INDEX IF NOT EXISTS uq_species_gbif_taxon_key ON species(gbif_taxon_key) WHERE gbif_taxon_key IS NOT NULL;

-- 4) Trees
CREATE TABLE IF NOT EXISTS trees (
  id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  species_id         INT REFERENCES species(id),

  planted_at         DATE,
  planted_by         VARCHAR,

  -- Use double precision for lat/lng (common + efficient for geo coords)
  location_lat       DOUBLE PRECISION NOT NULL,
  location_lng       DOUBLE PRECISION NOT NULL,

  -- Generated geometry point from lng/lat (note order: lng, lat)
  location           geometry(Point, 4326)
                     GENERATED ALWAYS AS (
                       ST_SetSRID(ST_MakePoint(location_lng, location_lat), 4326)
                     ) STORED,

  address_text       VARCHAR,

  adopted_by_user_id INT REFERENCES users(id),
  created_by_user_id INT NOT NULL REFERENCES users(id),

  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  approval_status    approval_status NOT NULL DEFAULT 'pending'
);

-- 5) Observations
CREATE TABLE IF NOT EXISTS observations (
  id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tree_id             INT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
  created_by_user_id  INT NOT NULL REFERENCES users(id),

  title              VARCHAR,
  note_text          TEXT,
  observed_at         TIMESTAMPTZ,

  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approval_status    approval_status NOT NULL DEFAULT 'pending'
);

-- 6) Observation Photos
CREATE TABLE IF NOT EXISTS observation_photos (
  id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_id     INT NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
  uploaded_by_user_id INT NOT NULL REFERENCES users(id),

  storage_key        VARCHAR NOT NULL,

  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approval_status    approval_status NOT NULL DEFAULT 'pending'
);

-- 7) Tree Detail History (versioned measurements)
CREATE TABLE IF NOT EXISTS tree_detail_history (
  id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  tree_id              INT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
  observation_id       INT REFERENCES observations(id) ON DELETE SET NULL,

  probable_age_years   INT,
  age_basis            VARCHAR,

  height_m             NUMERIC,
  height_method        VARCHAR,

  trunk_diameter_cm    NUMERIC,
  diameter_height_cm   NUMERIC,
  diameter_method      VARCHAR,

  canopy_diameter_m    NUMERIC,
  canopy_density       VARCHAR,

  recorded_by_user_id  INT NOT NULL REFERENCES users(id),

  recorded_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  approval_status      approval_status NOT NULL DEFAULT 'pending'
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_trees_species_id           ON trees(species_id);
CREATE INDEX IF NOT EXISTS idx_trees_adopted_by_user_id   ON trees(adopted_by_user_id);
CREATE INDEX IF NOT EXISTS idx_trees_lat_lng              ON trees(location_lat, location_lng);
CREATE INDEX IF NOT EXISTS idx_trees_approval_status      ON trees(approval_status);

-- Spatial index (best practice for geo queries like "within radius")
CREATE INDEX IF NOT EXISTS idx_trees_location_gist        ON trees USING GIST (location);

CREATE INDEX IF NOT EXISTS idx_observations_tree_id       ON observations(tree_id);
CREATE INDEX IF NOT EXISTS idx_observations_created_by    ON observations(created_by_user_id);
CREATE INDEX IF NOT EXISTS idx_observations_approval      ON observations(approval_status);

CREATE INDEX IF NOT EXISTS idx_observation_photos_obs_id  ON observation_photos(observation_id);
CREATE INDEX IF NOT EXISTS idx_observation_photos_uploader ON observation_photos(uploaded_by_user_id);
CREATE INDEX IF NOT EXISTS idx_observation_photos_approval ON observation_photos(approval_status);

CREATE INDEX IF NOT EXISTS idx_tree_detail_tree_id        ON tree_detail_history(tree_id);
CREATE INDEX IF NOT EXISTS idx_tree_detail_observation_id ON tree_detail_history(observation_id);
CREATE INDEX IF NOT EXISTS idx_tree_detail_recorded_at    ON tree_detail_history(recorded_at);
CREATE INDEX IF NOT EXISTS idx_tree_detail_tree_recorded  ON tree_detail_history(tree_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_tree_detail_approval       ON tree_detail_history(approval_status);

COMMIT;