-- 005_wildlife_health.sql
-- Adds wildlife species reference table, wildlife observation history,
-- and health observation history with associated issues.

BEGIN;

-- 1) Wildlife species reference table
CREATE TABLE IF NOT EXISTS wildlife_species (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  common_name     VARCHAR NOT NULL UNIQUE,
  scientific_name VARCHAR,
  taxon_key       INT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2) Tree wildlife history (one row per wildlife observation)
CREATE TABLE IF NOT EXISTS tree_wildlife_history (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tree_id             INT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
  observation_id      INT NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
  wildlife_species_id INT REFERENCES wildlife_species(id),
  life_stage          VARCHAR,
  count               INT,
  evidence_type       VARCHAR,
  behaviour           VARCHAR,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3) Tree health history (one row per health observation)
CREATE TABLE IF NOT EXISTS tree_health_history (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tree_id        INT NOT NULL REFERENCES trees(id) ON DELETE CASCADE,
  observation_id INT NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
  health_status  VARCHAR,
  risk_level     VARCHAR,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4) Health issues (1-to-many with tree_health_history)
CREATE TABLE IF NOT EXISTS tree_health_issues (
  id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tree_health_history_id INT NOT NULL REFERENCES tree_health_history(id) ON DELETE CASCADE,
  issue_type             VARCHAR,
  issue_name             VARCHAR,
  affected_part          VARCHAR,
  severity               VARCHAR,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_wildlife_history_tree_id       ON tree_wildlife_history(tree_id);
CREATE INDEX IF NOT EXISTS idx_wildlife_history_observation   ON tree_wildlife_history(observation_id);
CREATE INDEX IF NOT EXISTS idx_wildlife_history_species       ON tree_wildlife_history(wildlife_species_id);

CREATE INDEX IF NOT EXISTS idx_health_history_tree_id         ON tree_health_history(tree_id);
CREATE INDEX IF NOT EXISTS idx_health_history_observation     ON tree_health_history(observation_id);

CREATE INDEX IF NOT EXISTS idx_health_issues_health_id        ON tree_health_issues(tree_health_history_id);

-- Wildlife species seed data (common UK urban/woodland wildlife)
INSERT INTO wildlife_species (common_name, scientific_name, taxon_key) VALUES
  ('Robin',               'Erithacus rubecula',       2492483),
  ('Blue Tit',            'Cyanistes caeruleus',       2492413),
  ('Great Tit',           'Parus major',               2492390),
  ('Blackbird',           'Turdus merula',             2492557),
  ('Song Thrush',         'Turdus philomelos',         2492570),
  ('Woodpecker (Great Spotted)', 'Dendrocopos major',  2479737),
  ('Nuthatch',            'Sitta europaea',            2494068),
  ('Treecreeper',         'Certhia familiaris',        2494196),
  ('Jay',                 'Garrulus glandarius',       2482570),
  ('Squirrel (Grey)',     'Sciurus carolinensis',      2437038),
  ('Squirrel (Red)',      'Sciurus vulgaris',          2437034),
  ('Bat (Common Pipistrelle)', 'Pipistrellus pipistrellus', 2432386),
  ('Bat (Brown Long-eared)', 'Plecotus auritus',      2432467),
  ('Hedgehog',            'Erinaceus europaeus',       2433628),
  ('Fox',                 'Vulpes vulpes',             2433629),
  ('Badger',              'Meles meles',               2433699),
  ('Roe Deer',            'Capreolus capreolus',       2441187),
  ('Stag Beetle',         'Lucanus cervus',            1040876),
  ('Purple Hairstreak',   'Favonius quercus',          1920432),
  ('Oak Marble Gall Wasp', 'Andricus kollari',        1354498)
ON CONFLICT (common_name) DO NOTHING;

COMMIT;
