-- users
CREATE TABLE IF NOT EXISTS users (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR UNIQUE NOT NULL,
  password_hash VARCHAR NOT NULL,
  display_name  VARCHAR,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- sessions (refresh tokens)
CREATE TABLE IF NOT EXISTS sessions (
  id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_hash  VARCHAR UNIQUE NOT NULL,
  expires_at          TIMESTAMPTZ NOT NULL,
  last_used_at        TIMESTAMPTZ,
  revoked_at          TIMESTAMPTZ,
  device_label        VARCHAR,
  user_agent          VARCHAR,
  ip_address          VARCHAR,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at);